# boiler plate for docker
services:
  # edit with db information
  # db:
  #   image: ankane/pgvector:latest
  #   ports: ["5432:5432"]
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   volumes: ["postgres_data:/var/lib/postgresql/data"]
  
  db:
    image: ankane/pgvector:latest
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: icorps_dev_user
      POSTGRES_PASSWORD: icorps_dev_2026
      POSTGRES_DB: interview_info_app_db
    volumes: ["postgres_data:/var/lib/postgresql/data"]

  redis:
    image: redis:alpine
    ports: ["6379:6379"]

  minio:
    image: minio/minio
    ports: ["9000:9000", "9001:9001"]
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes: ["minio_data:/data"]

volumes:
  postgres_data:
  minio_data: